import google.generativeai as genai
from PIL import Image
import asyncio
import os
from typing import Optional
from app.config import settings


class GeminiService:
    def __init__(self):
        self.api_key = settings.gemini_api_key

        if self.api_key:
            genai.configure(api_key=self.api_key)
            # Using gemini-2.5-flash-image for image generation
            self.model = genai.GenerativeModel('gemini-2.5-flash-image')
        else:
            self.model = None

    async def generate_tryon(
        self,
        person_image_path: str,
        garment_image_path: str,
        custom_prompt: Optional[str] = None
    ) -> dict:
        """
        Generate virtual try-on image using Gemini

        Args:
            person_image_path: Path to user's photo
            garment_image_path: Path to garment image
            custom_prompt: Optional custom styling prompt

        Returns:
            dict with status, image_path, and message
        """

        if not self.model:
            return {
                "status": "error",
                "message": "Gemini API key not configured",
                "error": "API_KEY_MISSING"
            }

        try:
            # Load images
            person_img = Image.open(person_image_path)
            garment_img = Image.open(garment_image_path)

            # Construct prompt for virtual try-on
            base_prompt = """This is a VIRTUAL TRY-ON task. You will receive two images:

IMAGE 1 (FIRST IMAGE): A photo of a PERSON taken from a camera. This is the person who wants to try on clothes.
IMAGE 2 (SECOND IMAGE): A GARMENT/CLOTHING from a product catalog. This may be:
  - Just the garment/dress alone (product photo)
  - A model wearing the garment
  - A close-up/zoomed shot of the garment to show details

YOUR TASK: Generate a photorealistic image showing the PERSON FROM IMAGE 1 wearing the GARMENT FROM IMAGE 2.

⚠️ CRITICAL REQUIREMENTS - MUST FOLLOW:

1. FACE PRESERVATION (HIGHEST PRIORITY):
   - DO NOT modify, change, or alter the person's FACE in any way
   - Keep their facial features, skin tone, hair, facial structure EXACTLY as shown in Image 1
   - The face must be 100% identical to the original person
   - This is a virtual try-on, NOT a face swap or modification
   - Preserve their expression, facial proportions, and identity completely

2. GARMENT APPLICATION (MUST CHANGE CLOTHING):
   - You MUST replace the person's current clothing with the garment from Image 2
   - Extract ONLY the garment/clothing from Image 2 (ignore any model or background in catalog image)
   - Apply this exact garment to the person from Image 1
   - The clothing MUST be different from what they're currently wearing
   - Match the garment's exact colors, patterns, textures, and design details
   - Ensure realistic fit, natural draping, and proper garment physics

3. BODY & PROPORTIONS:
   - Keep the person's body type, build, and proportions from Image 1
   - Maintain their posture and stance
   - Preserve their skin tone exactly

4. VISUAL QUALITY:
   - Professional fashion photography lighting
   - Natural shadows and realistic fabric behavior
   - High-quality, photorealistic output
   - Clean background (prefer neutral/studio background)

IMPORTANT: The output image MUST show the person wearing DIFFERENT clothing than their input. This is the core purpose of virtual try-on.
"""

            if custom_prompt:
                base_prompt += f"\n\nAdditional style: {custom_prompt}"

            # Generate image with Gemini
            response = await asyncio.to_thread(
                self.model.generate_content,
                [base_prompt, person_img, garment_img]
            )

            # Extract generated image from response
            for part in response.parts:
                if hasattr(part, 'inline_data') and part.inline_data and part.inline_data.data:
                    # Save the generated image
                    result_filename = f"{os.path.basename(person_image_path).replace('_person', '_result')}"
                    result_path = os.path.join(settings.upload_dir, result_filename)

                    with open(result_path, 'wb') as f:
                        f.write(part.inline_data.data)

                    return {
                        "status": "success",
                        "image_path": result_path,
                        "message": "Virtual try-on generated successfully"
                    }

            # If no image was generated
            return {
                "status": "error",
                "message": "No image generated by Gemini",
                "error": "NO_IMAGE_OUTPUT"
            }

        except Exception as e:
            return {
                "status": "error",
                "message": f"Generation failed: {str(e)}",
                "error": str(e)
            }


# Singleton instance
gemini_service = GeminiService()
